### ISSUE TITLE
Licensing of the project 

### ISSUE THREAD

**Issue by onuralpszr** [Joshua-Ashton/vkroots#4]
Hello, I am working to bring vkroots into Fedora RPM so I can upgrade gamescope to latest version. We notice that LICENSE file partially cover and is it possible to add those license files under LICENSES/ folder. Or I can also open a PR for add those 3 license files as well.  

URL of RPM package process : https://bugzilla.redhat.com/show_bug.cgi?id=2175162

Thank you.

**Comment by misyltoad** [comment]
vkroots should never be distributed as a package as I am not committing to any version stability at this time.

**Comment by onuralpszr** [comment]
> vkroots should never be distributed as a package as I am not committing to any version stability at this time.

But It is in gamescope so should we just disable or what ? I mean I cannot just ignore that all the integration within vkroots. 

E.g : https://github.com/Plagman/gamescope/blob/297245cd7ecc8cde53aba06d439825024d002541/layer/VkLayer_FROG_gamescope_wsi.cpp#L4

So I should just ignore that part and not include it ?

**Comment by misyltoad** [comment]
No, you should still build with it.

It's a git submodule in Gamescope -- that submodule points to a specific version of vkroots.
Replacing the submodule with a packaged version  that is different may break randomly if vkroots updates.
I provide no guarantee of ABI or API compatibility at this stage of development.

**Comment by onuralpszr** [comment]
> No, you should still build with it.
> 
> It's a git submodule in Gamescope -- that submodule points to a specific version of vkroots. Replacing the submodule with a packaged version that is different may break randomly if vkroots updates. I provide no guarantee of ABI or API compatibility at this stage of development.

That is okay I will only use on gamescope for now so I can adjust based on that commit sha  and that is easy for me to setup. For the original question can I add the licenses or do you want to do it differently.

**Comment by misyltoad** [comment]
I am not sure your question, the generated code is `Apache-2.0 OR MIT`, the same as the Vulkan XML. It doesn't impact the license of Gamescope.

**Comment by onuralpszr** [comment]
> I am not sure your question, the generated code is `Apache-2.0 OR MIT`, the same as the Vulkan XML. It doesn't impact the license of Gamescope.

I know It does not effect Gamescope but I need it for vkroots to packaging.  Because in vkroots there is no proper license files (basically full text of LICENSE files) 

https://bugzilla.redhat.com/show_bug.cgi?id=2175162#c13

> Two things left:
> 
> * You need to put everything into a devel subpackage
> * You need to file an upstream issue for vkroots to include copies of the licenses referenced, since I could not find any...

**Comment by Conan-Kudo** [comment]
> I am not sure your question, the generated code is `Apache-2.0 OR MIT`, the same as the Vulkan XML. It doesn't impact the license of Gamescope.

Whether it's packaged separately or bundled in gamescope, there is still an outstanding problem: the actual texts of the licenses your project is under are not shipped in your sources. You need a copy of the LGPL-2.1, Apache-2.0, and MIT licenses in your source tree. It's particularly important for the MIT license since there are dozens of variants that call themselves "MIT" and nobody will know which one it is without the actual license text.
